In [21]:
import os

GM1 = '/home/ec2-user/SageMaker/data/GM_all_1945_1956/'
GM2 = '/home/ec2-user/SageMaker/data/GM_all_1957-1967/'

files = [GM1+f for f in os.listdir(GM1)]+[GM2+f for f in os.listdir(GM2)]
print(f'len(files)={len(files)}')

len(files)=2057868


In [22]:
from utils.general import info,ok, warning
import os
from tqdm import tqdm
from numpy import save, load
import pickle

def combine_files(file_):
    id_ = file_[:-13]
    g300 = 'precomputed/'+id_+'_glove300.npy'
    g600 = 'precomputed/'+id_+'_glove600.npy'
    if os.path.isfile(g300) and os.path.isfile(g600):
        print('entro!')
        output = 'precomputed/'+id_+'_glove.p'


        data = [load(g300),load(g600)]
        assert data[0].shape==(300,) and data[1].shape==(600,)
        pickle.dump(data,open(output,'wb'))
        if os.path.isfile(output):
            print('exit when saving')
            os.remove(g300)
            os.remove(g600)
        else:
            warning('FAILED TO SAVE.')
        


In [23]:
files = [f for f in os.listdir('precomputed/') if f.endswith('_glove600.npy')]
files


['1289484420_glove600.npy']

In [24]:
%%time
from utils.general import info, ok
import concurrent.futures
import datetime
writer = open('done.txt', 'w')
writer.write(f'{datetime.datetime.now()} Starting...\n')

info('Starting...')

with concurrent.futures.ThreadPoolExecutor(max_workers=3) as executor:
    executor.map(combine_files, files)
    
    
writer.write(f'{datetime.datetime.now()} Done!')
writer.close()
ok('Done!')

2022-03-22 15:12:54.423416 [ INFO  ] Starting...
entro!
exit when saving
2022-03-22 15:12:54.439754 [  OK   ] Done!
CPU times: user 4.78 ms, sys: 2.19 ms, total: 6.97 ms
Wall time: 17.1 ms


In [26]:
!rm 1316306628_glove.p

In [62]:
pickle.load(open('precomputed/1316306628_glove.p', 'rb'))[1]

array([-5.29903127e-03,  2.36712411e-01,  4.59458344e-02, -5.88498116e-02,
        6.24643005e-02,  4.06116657e-02,  8.70280936e-02, -1.01282418e-01,
        3.47736217e-02,  1.90603352e+00, -1.56536892e-01,  5.34800952e-03,
        8.31958745e-03,  9.93797928e-03, -3.08462828e-01, -1.02009080e-01,
        4.34732949e-03,  7.63322532e-01, -1.65308103e-01,  3.93569618e-02,
       -6.47938326e-02,  8.19159150e-02,  2.96556707e-02, -7.63859153e-02,
        1.62200835e-02, -2.64693350e-02, -1.00007445e-01,  9.74287558e-03,
        9.70853642e-02, -8.91554952e-02,  5.88497482e-02,  1.32679166e-02,
       -1.23813920e-01,  7.94324558e-03,  2.06641749e-01, -2.19153166e-01,
       -6.83111697e-02, -2.76526660e-02,  1.16936788e-02,  1.39467165e-01,
       -2.50451434e-02, -3.13919969e-02,  1.18139327e-01, -1.08812444e-01,
       -5.87829649e-02,  1.50538132e-01, -1.57086506e-01,  8.89399052e-02,
        1.40673831e-01, -5.53752817e-02, -1.24378307e-02,  6.96954429e-02,
        1.50925843e-02,  

In [56]:
load('precomputed/1316306628_glove300.npy')[-5:]

FileNotFoundError: [Errno 2] No such file or directory: 'precomputed/1316306628_glove300.npy'

1025290

In [43]:
import spacy
from numpy import load,save
from utils.tdmstudio import TDMStudio
nlp = spacy.load('en_core_web_lg', disable=['textcat','ner','parser','lemmatizer','tagger'])
nlp.tokenizer

def process_file(file_):
    title,text = TDMStudio.get_title_and_text(file_)
    if not title is None and not text is None:
        output = f"./precomputed/{file_.split('/')[-1][:-4]}_glove300.npy"
        if not os.path.isfile(output):
            X = nlp.tokenizer(f'{title}. {text}').vector
            save(output, X)
            del(X)
        del(output)
    del(title,text)
process_file(files[2])

In [39]:
!rm precomputed/*

In [40]:
!ls precomputed | wc -l

0


In [41]:
%%time
from utils.general import info, ok
import concurrent.futures
import datetime
writer = open('done.txt', 'w')
writer.write(f'{datetime.datetime.now()} Starting...\n')

info('Starting...')

with concurrent.futures.ThreadPoolExecutor(max_workers=3) as executor:
    executor.map(process_file, files[:2000])
    
    
writer.write(f'{datetime.datetime.now()} Done!')
writer.close()
ok('Done!')

2022-03-18 14:37:35.026062 [ INFO  ] Starting...
2022-03-18 14:37:46.402773 [  OK   ] Done!
CPU times: user 11.8 s, sys: 2.32 s, total: 14.1 s
Wall time: 11.4 s


In [21]:
load('./precomputed/1323614655_glove300.npy').shape

array([-3.75365764e-02,  8.24547932e-02, -7.16279969e-02, -4.33938168e-02,
        6.01135530e-02, -6.18309267e-02, -1.89493857e-02,  4.83585633e-02,
       -1.55454827e-02,  2.16811538e+00, -2.03832701e-01, -1.89375766e-02,
        6.72807172e-02, -5.52851669e-02, -3.75876911e-02, -6.06659688e-02,
       -1.11128129e-01,  1.03225660e+00, -1.35883629e-01, -7.90970866e-03,
        4.25903723e-02, -4.59617451e-02, -3.09190843e-02, -1.75308660e-02,
       -2.39690784e-02, -3.38351331e-03, -6.61650226e-02, -1.04455296e-02,
       -5.43173030e-02,  5.32380529e-02, -1.54791186e-02,  1.14362523e-01,
       -2.70199291e-02,  7.98858106e-02,  7.96253830e-02, -8.15682784e-02,
       -3.09338644e-02, -1.57738775e-02, -4.46906276e-02, -1.56271998e-02,
        1.73616502e-02,  1.13030791e-01,  4.88524791e-03, -4.82189469e-02,
        4.04829048e-02, -1.12770861e-02, -3.66155133e-02,  4.85042296e-03,
       -2.06274968e-02,  4.21019867e-02, -3.17739919e-02,  4.26244251e-02,
       -7.89265111e-02, -

In [9]:
nlp.tokenizer('hello world').vector

array([ 1.22825205e-01,  1.62070006e-01, -1.98879987e-01,  2.17849985e-02,
        4.17129993e-01, -5.19649982e-02,  3.00094992e-01,  4.74500656e-03,
       -1.27339497e-01,  1.75940990e+00, -2.98198521e-01, -5.31520009e-01,
        9.58340019e-02, -1.10948011e-01,  6.36099875e-02, -8.90085027e-02,
       -3.06479990e-01,  9.48599994e-01, -8.66500009e-03,  5.93170002e-02,
       -4.31229994e-02,  8.58594924e-02, -6.20179996e-02,  1.48400009e-01,
        9.59499925e-03, -1.88800007e-01,  1.83892995e-01, -1.08654000e-01,
        6.60129935e-02,  3.65982503e-01,  1.10872105e-01,  1.65569991e-01,
       -1.72460496e-01, -1.08801499e-01,  1.14099979e-02, -2.15905488e-01,
       -2.25299969e-02, -2.04996496e-01, -8.64600018e-03,  1.37630016e-01,
        1.95380002e-01, -1.98144495e-01, -1.13572001e-01, -1.51450038e-02,
       -1.76414996e-01,  5.54684997e-02, -4.31450009e-02, -7.37344995e-02,
        2.37168998e-01, -1.09114006e-01, -1.33163005e-01,  2.63469994e-01,
       -3.42079997e-01, -

In [13]:
import numpy as np
np.average([nlp.tokenizer('hello world')[0].vector, nlp.tokenizer('hello world')[1].vector],axis=0)

array([ 1.22825205e-01,  1.62070006e-01, -1.98879987e-01,  2.17849985e-02,
        4.17129993e-01, -5.19649982e-02,  3.00094992e-01,  4.74500656e-03,
       -1.27339497e-01,  1.75940990e+00, -2.98198521e-01, -5.31520009e-01,
        9.58340019e-02, -1.10948011e-01,  6.36099875e-02, -8.90085027e-02,
       -3.06479990e-01,  9.48599994e-01, -8.66500009e-03,  5.93170002e-02,
       -4.31229994e-02,  8.58594924e-02, -6.20179996e-02,  1.48400009e-01,
        9.59499925e-03, -1.88800007e-01,  1.83892995e-01, -1.08654000e-01,
        6.60129935e-02,  3.65982503e-01,  1.10872105e-01,  1.65569991e-01,
       -1.72460496e-01, -1.08801499e-01,  1.14099979e-02, -2.15905488e-01,
       -2.25299969e-02, -2.04996496e-01, -8.64600018e-03,  1.37630016e-01,
        1.95380002e-01, -1.98144495e-01, -1.13572001e-01, -1.51450038e-02,
       -1.76414996e-01,  5.54684997e-02, -4.31450009e-02, -7.37344995e-02,
        2.37168998e-01, -1.09114006e-01, -1.33163005e-01,  2.63469994e-01,
       -3.42079997e-01, -