In [6]:
import ipywidgets as widgets
slider = widgets.FloatSlider(value=0.5,
                     min=0,
                     max=1.0,
                     step=0.01,
                     description='Confidence:',
                     disabled=False,
                     continuous_update=False,
                     orientation='horizontal',
                     readout=True,
                     readout_format='.3f',
                     layout=widgets.Layout(width='237px'),
                     ) 
display(slider)

FloatSlider(value=0.5, continuous_update=False, description='Confidence:', layout=Layout(width='237px'), max=1…

In [10]:
slider.value

0.56

In [5]:
import warnings

def fxn():
    warnings.warn('deprecated', DeprecationWarning)
    
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    fxn()


In [10]:
def has_duplicated(list_):
    visited=set()
    has_duplicated=False
    i = 0
    while not has_duplicated and i<len(list_):
        has_duplicated = list_[i] in visited
        visited.add(list_[i])
        i+=1
    return has_duplicated

has_duplicated([0,1,2,3,4,0,6,7,8,9])

True

In [5]:
import os
dirpath='/home/ec2-user/SageMaker/mariano/notebooks/04. Model of DP/precomputed'
files = os.listdir(dirpath)
files = [file_ for file_ in files if  file_.endswith('.p')]
len(files)

2049401

In [9]:
import pickle

pickle.load(open(dirpath+'/'+files[0], 'rb'))[2]

<1x10000 sparse matrix of type '<class 'numpy.int32'>'
	with 118 stored elements in Compressed Sparse Row format>

In [11]:
import numpy as np 
from scipy.sparse import csr_matrix

# create a 2-D representation of the matrix
A = np.array([[1, 0, 0, 0, 0, 0], [0, 0, 2, 0, 0, 1],\
 [0, 0, 0, 2, 0, 0]])
print("Dense matrix representation: \n", A)

# convert to sparse matrix representation 
S = csr_matrix(A)
S

Dense matrix representation: 
 [[1 0 0 0 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [ ]:

S